version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: unykorn_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: unykorn
      POSTGRES_PASSWORD: unykorn
      POSTGRES_DB: orgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
