name: Manual Backend Redeploy

on:
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger via Render Deploy Hook
        if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          echo "Triggering Render deploy via Deploy Hook"
          curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
      - name: Fail if no hook configured
        if: ${{ secrets.RENDER_DEPLOY_HOOK == '' }}
        run: |
          echo "No RENDER_DEPLOY_HOOK secret configured." && exit 1
